builds:
  - binary: goreleaser-test
    main: main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/epy0n0ff/goreleaser-test/cmd/goreleaser-test/cmd.version={{.Version}}" -X "github.com/epy0n0ff/goreleaser-test/cmd/goreleaser-test/cmd.commit={{.Commit}}"