builds:
  - binary: goreleaser-test
    main: main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/epy0n0ff/goreleaser-test/cmd.version=v0.0.2" -X "github.com/epy0n0ff/goreleaser-test/cmd.commit=abcd"